---
# tasks file for /etc/ansible/roles/apache

 - name: install apache
   yum:
     name: httpd 
     state: present
 - name: service
   service:
      name: httpd
      state: started
      enabled: yes  
 - name: copy file to projcet
   copy:
    src: files/index.html
    dest: /var/www/html/index.html
 - name: copy file to project   
   copy: 
    src: files/virt.conf
    dest: /etc/httpd/conf.d/virt.conf
 - name: ssl
   command: openssl genrsa -out elinuxbook.key 2048
 - name: ssl
   command: openssl req -newkey rsa:2048 -nodes -keyout elinuxbook.key -out elinuxbook.csr -subj "/C=US/ST=New York/L=Brooklyn/O=Example Brooklyn Company/CN={{dns}}"
 - name: ssl
   command: openssl x509 -req -days 1095 -in elinuxbook.csr -signkey elinuxbook.key -out elinuxbook.crt
 - name:
   shell: cp elinuxbook.crt /etc/pki/tls/certs/
 - name: 
   shell: cp elinuxbook.key /etc/pki/tls/private/
 - name:
   shell: cp elinuxbook.csr /etc/pki/tls/private/
 - name: mod_ssl
   yum: name=mod_ssl state=latest
 - name: line in file
   lineinfile:
     path: /etc/httpd/conf.d/ssl.conf
     regexp: '^SSLCertificateFile'
     line: SSLCertificateFile /etc/pki/tls/certs/elinuxbook.crt
 - name: line in file
   lineinfile:
      path: /etc/httpd/conf.d/ssl.conf
      regexp: '^SSLCertificateKeyFile'
      line: SSLCertificateKeyFile /etc/pki/tls/private/elinuxbook.key
   notify:
   - restart apache 


